# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/taehong/Downloads/PROG Github/PROG1700_SourceCode/w0445964_MinT/Final Project/FinalProject.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listCountries = QtWidgets.QListWidget(self.centralwidget)
        self.listCountries.setGeometry(QtCore.QRect(10, 30, 256, 631))
        self.listCountries.setObjectName("listCountries")
        self.labelChooseCountryMessage = QtWidgets.QLabel(self.centralwidget)
        self.labelChooseCountryMessage.setGeometry(QtCore.QRect(10, 10, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelChooseCountryMessage.setFont(font)
        self.labelChooseCountryMessage.setObjectName("labelChooseCountryMessage")
        self.labelCountryName = QtWidgets.QLabel(self.centralwidget)
        self.labelCountryName.setGeometry(QtCore.QRect(270, 30, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.labelCountryName.setFont(font)
        self.labelCountryName.setText("")
        self.labelCountryName.setObjectName("labelCountryName")
        self.labelPicture = QtWidgets.QLabel(self.centralwidget)
        self.labelPicture.setGeometry(QtCore.QRect(280, 80, 311, 151))
        self.labelPicture.setText("")
        self.labelPicture.setObjectName("labelPicture")
        self.labelPopulation = QtWidgets.QLabel(self.centralwidget)
        self.labelPopulation.setEnabled(True)
        self.labelPopulation.setGeometry(QtCore.QRect(280, 290, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelPopulation.setFont(font)
        self.labelPopulation.setObjectName("labelPopulation")
        self.lineEditInputUserUpdate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditInputUserUpdate.setGeometry(QtCore.QRect(370, 290, 231, 21))
        self.lineEditInputUserUpdate.setObjectName("lineEditInputUserUpdate")
        self.pushButtonUpdatePopulation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUpdatePopulation.setGeometry(QtCore.QRect(445, 320, 161, 41))
        self.pushButtonUpdatePopulation.setObjectName("pushButtonUpdatePopulation")
        self.labelTotalAreaIn = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalAreaIn.setGeometry(QtCore.QRect(280, 390, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelTotalAreaIn.setFont(font)
        self.labelTotalAreaIn.setObjectName("labelTotalAreaIn")
        self.comboBoxMilesOrKilometers = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxMilesOrKilometers.setGeometry(QtCore.QRect(370, 390, 101, 21))
        self.comboBoxMilesOrKilometers.setAcceptDrops(False)
        self.comboBoxMilesOrKilometers.setObjectName("comboBoxMilesOrKilometers")
        self.comboBoxMilesOrKilometers.addItem("")
        self.comboBoxMilesOrKilometers.addItem("")
        self.labelAreaNumber = QtWidgets.QLabel(self.centralwidget)
        self.labelAreaNumber.setGeometry(QtCore.QRect(510, 392, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelAreaNumber.setFont(font)
        self.labelAreaNumber.setText("")
        self.labelAreaNumber.setObjectName("labelAreaNumber")
        self.groupBoxPopulationDensity = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPopulationDensity.setGeometry(QtCore.QRect(280, 460, 311, 121))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBoxPopulationDensity.setFont(font)
        self.groupBoxPopulationDensity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBoxPopulationDensity.setObjectName("groupBoxPopulationDensity")
        self.labelPopulationDensity = QtWidgets.QLabel(self.groupBoxPopulationDensity)
        self.labelPopulationDensity.setGeometry(QtCore.QRect(230, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelPopulationDensity.setFont(font)
        self.labelPopulationDensity.setText("")
        self.labelPopulationDensity.setObjectName("labelPopulationDensity")
        self.radioButtonPerSqMile = QtWidgets.QRadioButton(self.groupBoxPopulationDensity)
        self.radioButtonPerSqMile.setEnabled(True)
        self.radioButtonPerSqMile.setGeometry(QtCore.QRect(10, 50, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButtonPerSqMile.setFont(font)
        self.radioButtonPerSqMile.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButtonPerSqMile.setChecked(True)
        self.radioButtonPerSqMile.setObjectName("radioButtonPerSqMile")
        self.radioButtonPerSqKM = QtWidgets.QRadioButton(self.groupBoxPopulationDensity)
        self.radioButtonPerSqKM.setGeometry(QtCore.QRect(10, 80, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButtonPerSqKM.setFont(font)
        self.radioButtonPerSqKM.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButtonPerSqKM.setObjectName("radioButtonPerSqKM")
        self.labelPercentageText = QtWidgets.QLabel(self.centralwidget)
        self.labelPercentageText.setGeometry(QtCore.QRect(280, 620, 223, 18))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelPercentageText.setFont(font)
        self.labelPercentageText.setObjectName("labelPercentageText")
        self.labelPercentageNumber = QtWidgets.QLabel(self.centralwidget)
        self.labelPercentageNumber.setGeometry(QtCore.QRect(510, 620, 111, 19))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelPercentageNumber.setFont(font)
        self.labelPercentageNumber.setText("")
        self.labelPercentageNumber.setObjectName("labelPercentageNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Countries = QtWidgets.QAction(MainWindow)
        self.actionLoad_Countries.setObjectName("actionLoad_Countries")
        self.actionSave_To_File = QtWidgets.QAction(MainWindow)
        self.actionSave_To_File.setObjectName("actionSave_To_File")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionsdsd = QtWidgets.QAction(MainWindow)
        self.actionsdsd.setObjectName("actionsdsd")
        self.menuFile.addAction(self.actionLoad_Countries)
        self.menuFile.addAction(self.actionSave_To_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.labelChooseCountryMessage.setBuddy(self.labelChooseCountryMessage)
        self.labelCountryName.setBuddy(self.labelChooseCountryMessage)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Countries of the World"))
        self.labelChooseCountryMessage.setText(_translate("MainWindow", "Choose a country from the list:"))
        self.labelPopulation.setText(_translate("MainWindow", "Population:"))
        self.pushButtonUpdatePopulation.setText(_translate("MainWindow", "Update Population"))
        self.labelTotalAreaIn.setText(_translate("MainWindow", "Total Area in"))
        self.comboBoxMilesOrKilometers.setItemText(0, _translate("MainWindow", "Sq. Miles"))
        self.comboBoxMilesOrKilometers.setItemText(1, _translate("MainWindow", "Sq. KMs"))
        self.groupBoxPopulationDensity.setTitle(_translate("MainWindow", "Population Density"))
        self.radioButtonPerSqMile.setText(_translate("MainWindow", "Per Square Mile"))
        self.radioButtonPerSqKM.setText(_translate("MainWindow", "Per Square KM"))
        self.labelPercentageText.setText(_translate("MainWindow", "Percentage of World Population:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Countries.setText(_translate("MainWindow", "Load Countries"))
        self.actionSave_To_File.setText(_translate("MainWindow", "Save To File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit_2.setText(_translate("MainWindow", " Exit"))
        self.actionsdsd.setText(_translate("MainWindow", "sdsd"))

